"""Initial

Revision ID: 1cbd3532f5c0
Revises: 
Create Date: 2023-07-19 02:49:22.360268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbd3532f5c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'black_list', ['id'])
    op.create_unique_constraint(None, 'booking', ['id'])
    op.create_unique_constraint(None, 'city', ['id'])
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'place', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'place', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_constraint(None, 'booking', type_='unique')
    op.drop_constraint(None, 'black_list', type_='unique')
    # ### end Alembic commands ###
